defmodule Support.Bids do
  def all do
    [
      {:one, :clubs},
      {:one, :diamonds},
      {:one, :hearts},
      {:one, :spades},
      {:one, :no_trump},
      {:two, :clubs},
      {:two, :diamonds},
      {:two, :hearts},
      {:two, :spades},
      {:two, :no_trump},
      {:three, :clubs},
      {:three, :diamonds},
      {:three, :hearts},
      {:three, :spades},
      {:three, :no_trump},
      {:four, :clubs},
      {:four, :diamonds},
      {:four, :hearts},
      {:four, :spades},
      {:four, :no_trump},
      {:five, :clubs},
      {:five, :diamonds},
      {:five, :hearts},
      {:five, :spades},
      {:five, :no_trump},
      {:six, :clubs},
      {:six, :diamonds},
      {:six, :hearts},
      {:six, :spades},
      {:six, :no_trump},
      {:seven, :clubs},
      {:seven, :diamonds},
      {:seven, :hearts},
      {:seven, :spades},
      {:seven, :no_trump}
    ]
  end
end
